### ISSUE TITLE
Would be nice if you could run with python -m omnidep ...

### ISSUE THREAD

**Issue by johnmreynolds** [sjjessop/omnidep#2]
Currently if you want to run omnidep as a module (if for whatever reason you don't trust the script paths), you currently need to do:

python -m omnidep.main ...

rather than

python -m omnidep ...

which is common for most python tools.

This isn't a major issue, as it does seem to work fine as long as you add the '.main'.

**Comment by sjjessop** [comment]
Fixed in 0.3.4
